# srcs/docker-compose.yml

version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - wp_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network
    
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception_network

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_network

volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: volume
      device: /Users/kimjaehwan/jaekim/42seoul/inception/srcs/requirements/tools/wordpress
      o: bind
  db_volume:
    driver: local
    driver_opts:
      type: volume
      device: /Users/kimjaehwan/jaekim/42seoul/inception/srcs/requirements/tools/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge