# 도커 컴포즈의 버전을 명시한다. 1.27.4 버전부터는 버전을 명시하지 않아도 된다.
# 하지만, 버전을 명시하는 것을 권장한다.
version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    command: ["nginx", "-g", "daemon off;"]

  mariadb: